language: c
sudo: false

compiler:
  - gcc
  - clang

addons:
    apt:
        packages:
            - libjudy-dev
            - libvorbis-dev
            - libportaudio-dev
            - libtalloc-dev

script:
    - make -j2 -k quiet=1
    - make -k check quiet=1
